Page({
  data: {
    items: [{
      id: "1",
      src: "https://s7.postimg.cc/rzquyo22z/image.jpg"
    }, {
      id: "2",
      src: "https://s7.postimg.cc/xdytxcbm3/image.jpg"
    }, {
      id: "3",
      src: "https://s7.postimg.cc/brjtgf7xn/image.jpg"
    }, {
      id: "4",
      src: "https://s7.postimg.cc/9zqulloln/image.jpg"
    }, {
      id: "5",
      src: "https://s7.postimg.cc/4oby0xctn/image.jpg"
    }, {
      id: "6",
      src: "https://s7.postimg.cc/elmyu0faj/image.jpg"
    }, {
      id: "7",
      src: "https://s7.postimg.cc/lc3g3gxbf/image.jpg"
    }, {
      id: "8",
      src: "https://s7.postimg.cc/xf8rqyg2j/image.jpg"
    }, {
      id: "9",
      src: "https://s7.postimg.cc/76xn1ngkb/image.jpg"
    }, {
      id: "10",
      src: "https://s7.postimg.cc/emwwngrez/image.jpg"
    }, {
      id: "11",
      src: "https://s7.postimg.cc/uxx0jsyrv/image.jpg"
    }, {
      id: "12",
      src: "https://s7.postimg.cc/yhiy9om2z/image.jpg"
    }, {
      id: "13",
      src: "https://s7.postimg.cc/pmi3z6kfv/image.jpg"
    }, {
      id: "14",
      src: "https://s7.postimg.cc/53n7tm6d7/image.jpg"
    }, {
      id: "15",
      src: "https://s7.postimg.cc/oy99frgfv/image.jpg"
    }, {
      id: "16",
      src: "https://s7.postimg.cc/ja2yow6yj/image.jpg"
    }, {
      id: "17",
      src: "https://s7.postimg.cc/d959rts23/image.jpg"
    }, {
      id: "18",
      src: "https://s9.postimg.cc/8jzmxmvtb/dining_room.png"
    }]
  },
})